version: "3"
services:
  web:
    build:
      context: ./apache-php
    ports: 
      - ${PORT_WEB}:80
    links:
      - mysql
    privileged: true
    volumes:
      - ./html:/var/www/html/
      - ./apache-php/httpd.conf:/etc/httpd/conf/httpd.conf
    container_name: ${COMPOSE_PROJECT_NAME}
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${COMPOSE_PROJECT_NAME}
    ports:
      - ${PORT_DB}:3306
    volumes:
      - ./mysql-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${PASSWORD}
    links:
      - mysql
    ports:
      - ${PORT_PHPMYADMIN}:80


